Updated DB related changes
santiaguf/node-todo-app pull request #10
Opened 2022-10-15 04:43 UTC by iHaroon29

Current Changes:-

1. Dedicated DB connection file.
2. Model-logic has been separated from the controller file.
3. The Find route for Tasks and Users has also been updated. (Use Postman to test)

2022-10-20 18:01 UTC, iHaroon29 commented
Hi @santiaguf, Hope this commit would suffice. Please lemme know if there are any changes you want to be done.

2022-10-20 18:12 UTC, santiaguf commented
@iHaroon29 I will check your PR in detail this weekend.

2022-10-22 21:40 UTC, santiaguf requested changes
Please review my comments, and test it again in your local environment.
you should see a user list in `http://localhost:3005/users-ui/`

2022-10-22 21:40 UTC, santiaguf commented on app/routes/user.routes.js
> +  .get('/:userId', find)
you need to include a method to get all users.
```
   .get('/', findAll)
```

2022-10-22 21:40 UTC, santiaguf commented on app/routes/task.routes.js
> +  .get('/:taskId?', find)
You need to include a method to get all tasks.
```
 .get('/', findAll)
```

2022-10-22 21:40 UTC, santiaguf commented on app/config/dbConfig.js
> +const dbConnection = createConnection(process.env.dbURLProd, {
```
process.env.DB_URL || process.env.DB_URL_PROD
```

2022-10-22 21:40 UTC, santiaguf commented on app/models/user.model.js
> +UserSchema.statics.findUsers = async function (data) {
This method should retrieve one user (by id).

2026-04-30 21:13 UTC, santiaguf commented
as this is too old, i will close this PR

2026-04-30 21:13 UTC, closed without merging